python_tests(
    name="tests",
    dependencies=[
        #"cheeseshop:project-version",
        "cheeseshop:main-project-version",
        ":cassettes",
    ],
)

resources(
    name="cassettes",
    sources=["cassettes/*"],
)
