load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("@rules_python//python:py_binary.bzl", "py_binary")

py_binary(
  name = "main",
  srcs = ["main.py"],
  deps = [
      "@pypi//loguru",
  ],
  python_version="3.11"
)

genrule(
    name = "python-helper",
    outs = ["data.json"],
    toolchains=["@rules_python//python:current_py_toolchain"],
    # Path to Python interpreter via a MAKE variable
    # https://rules-python.readthedocs.io/en/latest/toolchains.html#toolchain-usage-in-other-rules
    cmd = "$(PYTHON3) -c \"import json; print(json.dumps({'a': 'b'}, indent=2))\" > $@",
)

# flag to request using a local Python interpreter
config_setting(
    name = "is_py_local",
    flag_values = {":py": "local-3_12"},
)
string_flag(
    name = "py",
    build_setting_default = "",
)
