bazel_dep(name = "rules_python", version = "1.4.1")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.11",
    requirements_lock = "//requirements:requirements.lock",
)
pip.parse(
    hub_name = "pypi-tools",
    python_version = "3.11",
    requirements_lock = "//requirements:requirements-tools.lock",
)
use_repo(pip, "pypi")
use_repo(pip, "pypi-tools")
