[GLOBAL]
pants_version = "2.14.0"

pythonpath = ["%(buildroot)s/pants-plugins"]

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  # plugins
  "project_version",
]

[python]
enable_resolves = true
interpreter_constraints = ["CPython==3.9.*", "CPython==3.10.*"]

[python.resolves]
python-default = "requirements/requirements.lock"

[python-bootstrap]
# https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path
search_path = ["<PYENV_LOCAL>", "<PATH>"]

[anonymous-telemetry]
enabled = true
repo_id = "df6470e5-420b-4930-b6e6-638cc06ffe0b"

[source]
# https://www.pantsbuild.org/docs/source-roots#no-source-root
root_patterns = [
    "/", "pants-plugins"
]

[flake8]
version = "flake8==5.0.4"
lockfile = "requirements/flake8.lock"

[mypy]
version = "mypy==0.971"
lockfile = "requirements/mypy.lock"
extra_type_stubs = [
    "types-requests==2.28.9",
    "types-python-dateutil==2.8.19",
    "types-setuptools==65.1.0",
]

[black]
version = "black==22.6.0"
lockfile = "requirements/black.lock"

[docformatter]
version = "docformatter>=1.4,<1.5"
lockfile = "requirements/docformatter.lock"

[isort]
version = "isort==5.10.1"
lockfile = "requirements/isort.lock"
extra_requirements.add = [
    "setuptools"
]

[pytest]
# https://www.pantsbuild.org/docs/reference-pytest#section-extra-requirements
extra_requirements.add = [
  "pytest-vcr",
]
lockfile = "requirements/pytest.lock"
args = ["-v", "--vcr-record=none"]
