[GLOBAL]
pants_version = "2.13.0rc1"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.typecheck.mypy",
]

[python]
enable_resolves = true

[python.resolves]
python-default = "requirements/requirements.lock"

[python-bootstrap]
# https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path
search_path = ["<PYENV_LOCAL>", "<PATH>"]

[anonymous-telemetry]
enabled = true
repo_id = "df6470e5-420b-4930-b6e6-638cc06ffe0b"

[source]
# https://www.pantsbuild.org/docs/source-roots#no-source-root
root_patterns = [
    "/"
]

[flake8]
version = "flake8==5.0.4"
lockfile = "requirements/flake8.lock"

[mypy]
version = "mypy==0.971"
lockfile = "requirements/mypy.lock"

[black]
version = "black==22.6.0"
lockfile = "requirements/black.lock"

[pytest]
# https://www.pantsbuild.org/docs/reference-pytest#section-extra-requirements
extra_requirements.add = [
  "pytest-vcr",
]
lockfile = "requirements/pytest.lock"
args = ["-v", "--vcr-record=none"]
