load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_pex_binary")

# py_binary from rules_python cannot be used in py_pex_binary, so it must
# be coming from aspect_rules_py
py_binary(
    name = "cli",
    srcs = ["cli.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//cheeseshop/cli/utils",
        "//cheeseshop/repository",
        "@pypi//click",
        "@pypi//loguru",
    ],
)

py_pex_binary(
    name = "cli-pex",
    binary = ":cli",
    python_interpreter_constraints = [
        "CPython==3.11.*",
        "CPython==3.12.*",
    ],
)
