python_requirements(
    name="requirements-dev",
    source="requirements-dev.txt",
)

python_requirements(
    name="requirements-test",
    source="requirements-test.txt",
)

python_requirements(
    name="requirements",
)
