python_requirements(
    name="requirements",
    source="requirements.txt",
    resolve="python-default",
)

python_requirements(
    name="requirements-test",
    source="requirements-test.txt",
    resolve="testtools",
)

python_requirements(
    name="requirements-dev",
    source="requirements-dev.txt",
    resolve="devtools",
)
