python_sources(
    overrides={
        "version.py": {"dependencies": ["//:deps-group-1"]},
    }
)

resource(
    name="project-version",
    source="VERSION",
)

version_file(
    name="main-project-version",
    source="VERSION",
)
