python_sources()

resource(
    name="project-version",
    source="VERSION",
)


# ./pants project-version ::
# (ProjectVersionFileView(path='cheeseshop/VERSION', version='0.0.1'),)

version_target(name="main-project-version", source="VERSION")

