name: CI validations

on: [pull_request]

jobs:
  build:
    name: "CI validations"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install yamllint==1.27.1

      - name: Validate YAML files
        run: |
          yamllint .github --no-warnings
