name: Pants build

on: [pull_request]

jobs:
  build:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Tell Pants to use Python ${{ matrix.python-version }}
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        run: 'echo "PY=python${{ matrix.python-version }}" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=[''==${{ matrix.python-version
        }}.*'']" >> $GITHUB_ENV
        '
      - name: Run tests
        run: |
          ./pants test ::
