name: Pants build

on: [pull_request]

jobs:
  build:
    name: "Run Pants build"
    runs-on: ubuntu-latest
    env:
      PANTS_CONFIG_FILES: pants.ci.toml

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Tell Pants to use Python ${{ matrix.python-version }}
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        run: |
          echo "PY=python${{ matrix.python-version }}" >> $GITHUB_ENV &&
          echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=['==${{ matrix.python-version}}.*']" >> $GITHUB_ENV

      - name: List environment variables
        run: |
          echo "${{ env.PY }}"
          echo "${{ env.PANTS_PYTHON_INTERPRETER_CONSTRAINTS }}"

      - name: Bootstrap Pants
        run: |
          ./pants version

      - name: Run tests
        run: |
          ./pants test ::

      - name: Run linters
        run: |
          ./pants update-build-files --check ::
          ./pants lint ::

      - name: Package and check Python wheel
        run: |
          ./pants package //:cheeseshop-query-wheel
          python3 -m venv .venv
          source .venv/bin/activate
          pip install dist/*.whl
          cheeseshop-query
          cheeseshop-query --version

