name: Test project

on: [push]

jobs:
  test:
    name: "Test project"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pip==22.0.4
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-test.txt

      - name: Unit tests
        run: |
          pytest -v -k "not cli" --ignore="pants-plugins" \
            --ignore="tests/pantstests" --vcr-record=none

      - name: Application tests
        run: |
          pytest -v -k "cli" --ignore="pants-plugins" \
            --ignore="tests/pantstests" --vcr-record=none
